version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 705581497453.dkr.ecr.ap-northeast-1.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - REPOSITORY_URI=$REPOSITORY_URI_NGINX
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI_NGINX:latest -f ./docker/nginx/Dockerfile .
      - docker tag $REPOSITORY_URI_NGINX:latest $REPOSITORY_URI_NGINX:$IMAGE_TAG
      - docker build -t $REPOSITORY_URI_PHP:latest -f ./docker/php/Dockerfile .
      - docker tag $REPOSITORY_URI_PHP:latest $REPOSITORY_URI_PHP:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI_NGINX:latest
      - docker push $REPOSITORY_URI_NGINX:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"}]' $REPOSITORY_URI_NGINX:$IMAGE_TAG > imagedefinitions.json
      - docker push $REPOSITORY_URI_PHP:latest
      - docker push $REPOSITORY_URI_PHP:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"php","imageUri":"%s"}]' $REPOSITORY_URI_PHP:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json